### ISSUE TITLE
Cypress optimization

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza-e2e-cypress#40]
## **Test isolation:**
Every webapp should be isolated in terms of execution, the last webapp should not be dependant of the data that was created in earlier testing cases.
Ie, Compose tests should not rely on users that were created in Admin test case.
Every webapp should have its own provisioning

## **Page load polling:**
Take care of slow page loading in certain cases, do not use sleep mechanisms, since those are wasteful and not always useful.
Ie, sleeping for 10seconds would in 90% cases be too slow, but in some cases not enough.
Need to find some internal functions/helpers of Cypress that try to load page every n seconds for x tries

## **Commands for each webapp test run**
If we're gonna test in parallel, we need the list of webapp spec files and a way to run them with Cypress
Example: `yarn cypress run --spec '<path-to-spec-file>'`

### Checklist

- [ ] test case provisioning and cleanup after run
- [ ] cypress page load delay helper
- [ ] prepare commands for each webapp test run

**Comment by Bojan-Svirkov** [comment]
Comment from Katrin:

Stuff to consider:
- Test isolation: running webapps in isolation could be achieved. We can create a file containing the data needed for our webapp. The file could be an .sql. There's one problem: some tests require switching from one webapp to another; ie: testing permissions, enabling apps in admin and more. An idea is to run tests selectively, if possible
- Page load polling: this is mainly used in admin and compose. Locally ran tests will fail if we're not careful here
- Commands for each webapp test run: in order for this to work don't we need a strong machine with a good processor and a lot of ram? (thinking out loud; I'm a girl and don't know much; often overhearing things from here and there and not always piecing them together well). This may work when testing all webapps excluding compose because it has the most tests. I have a feeling that if we run compose + other webapp tests, there will be fireworks. That's all for now. Cheers beers

**Comment by Bojan-Svirkov** [comment]
Comment from Peter:

Test Isolation: We have the ability to provision data on server startup (yaml files) so that could be arranged in that way.
I agree, some scenarios could be tricky with jumping from webapp to another, maybe we can isolate those and try to see if there's a possibility to use only one webapp and maybe get/put the data via API (ie in admin test, do all the admin testing, if something needs to be done on compose, call the compose API, since cypress is js).
Page load polling: Why would the tests fail if we do it like that?
Commands for each webapp test run: We do need a strong machine and whole lotta RAM if we do it on the same machine, a lot of times the test runners are being used in containers that can be on different machines.
So yeah, a really good point, but there's no issue in running these tests synchronous and if/when at all we'll need to do it in parallel it won't be a hassle.
Also, is it not easier to be able to test locally only a specific app and not wait for all of them? I guess if you're using cypress UI then it's easier yeah.

Long story long, if the separation is doable without too many hassles and hacks, I think it's worth it.

**Comment by Bojan-Svirkov** [comment]
Comment from Katrin:

Page load polling: compared to inputs, textareas, labels, some checkboxes need more time in order for their values to be bound and graphs also need more time to be loaded. ie: if we don't wait for the graphs in admin's dashboard to be loaded before clicking wherever we desire an error will be thrown and cypress won't run any other tests. This is a pain because dashboard is the first view we land on when loading admin.
Commands for each webapp test run: it is a lot easier to test one webapp at a time. The end result is to run an index file containing all of the tests but that could be changed to running one app's index file (containing all of its tests) at a time. Nothing is fixated. Whichever's best.

**Comment by petergrlica** [comment]
Closing this issue as we resolved the optimization discussion as it will be implemented in one of the next iterations of testing (which will be a bit more isolated and scenario-driven).
Created https://github.com/cortezaproject/corteza-e2e-cypress/issues/47 for enabling cypress testing on a scheduled basis, just to have an overview.
