### ISSUE TITLE
Cypress - Sidebar (Second layer of testing)

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza-e2e-cypress#41]
### Description

This ticket is in regards to testing the sidebar and it's functionalities. For example hovering over it, using the pin button, checking the dropdown etc..

1. Compose

- [x] Test search func
- [x] Manage namespaces -> see if this button takes you to desired place

2.  Reporter

- [x] Test search func

3. Workflow

- [x] Check if the Home button takes you to the expected place

**Comment by katrinDY** [comment]
description to be edited; slight adjustments needed and more contents to be added

**Comment by katrinDY** [comment]
Cypress ids added.

Branch `2022.9.x-feature-add-cypress-id-sidebar-second-layer`

**Comment by Bojan-Svirkov** [comment]
https://github.com/cortezaproject/corteza-e2e-cypress/commit/e6af02dd8028ace6918ce384464badfbaa93767a

**Comment by katrinDY** [comment]
### Code for branches:
**22.9**: [8fed022](https://github.com/cortezaproject/corteza/commit/8fed022c1d5494c28e0ca71c3278de786fe91ad8) 
**23.3**: [2aa086f](https://github.com/cortezaproject/corteza/commit/2aa086fa7586f52084330b37fa6fbb1b18a3b829)
