### ISSUE TITLE
Cypress - Admin - Settings (Second layer of testing)

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza-e2e-cypress#43]
## Settings (System)

- [ ] Authentication: Test all the checkboxes
- [ ] Password constraints: Test the minimum length, number of digits and special characters
- [ ] Multi-factor authentication: Test all the check boxes (this will need to be checked if it can be tested since it requires sending emails)
- [ ] Test the authentication email sender mail
- [ ] Test the external authentication providers and add an OIDC provider and see if it is displayed on the log in screen

## Settings (Compose)

- [ ] Test the page attachments max size and file type whitelist
- [ ] Test the record attachments max size and file type whitelist
- [ ] Test the user interface’s checkboxes

## Settings (User Interface)

- [ ] Test the main logo
- [ ] Test the icon logo
- [ ] Test the Topbar checkboxes

**Comment by katrinDY** [comment]
Broke down the ticket into several smaller issues
