### ISSUE TITLE
Cypress - Pagination & sorting

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza-e2e-cypress#45]
**Note**: _This was discussed idea with Peter, if we could implement like a custom function that will be included in all the required files that the pagination and sorting will need to be tested. So if we create a function, a pile of code that will be able to test the sorting of users lets say and test the pagination of users in admin, we can then reuse that function everywhere when needed. This is just an idea for now and will need to decide whether is smart to have something like this in cypress or just do that manually._

## Compose pagination and sorting:

- [x] Create record list that will have a limit so we will have more pages
- [x] Enable `Show total record count` and once you add all the records, check if the total record count is the correct number
- [x] Click on next page and see if you are taken to the second page and what is the record count
- [x] Check if `One record` is displayed in total record count when you have one record. Use the search for this so that one record will be shown.
- [x] Check if 2 records, 3 records are shown if you have 2 or 3 records respectively. Use again the search for this action
- [x] Test the full page navigation
- [x] Test the first & last page buttons (not just next and previous)
- [x] Test the sorting (take for example a sorting of numbers and see when you click it if the numbers are shown in ascending order and when you click it again if the numbers are shown in descending order)

## Add ids to
- [x] show pagination
- [x] show paging
- [x] records per page
- [x] record range in pagination
- [x] single record count in pagination
- [x] full page navigation buttons
- [x] partial page navigation buttons
- [x] recordlist table

**Comment by katrinDY** [comment]
Cypress ids added; branch `2022.9.x-feature-add-cypress-id-compose-pagination-and-sorting`

**Comment by Bojan-Svirkov** [comment]
https://github.com/cortezaproject/corteza-e2e-cypress/pull/57

**Comment by Bojan-Svirkov** [comment]
https://github.com/cortezaproject/corteza-e2e-cypress/commit/4f246f2a8e89bf1809594cc49e8f9685c3ce1548
