### ISSUE TITLE
Cypress - Sidebar (First layer of testing)

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza-e2e-cypress#51]
## Description:
Add cypress tests for common sidebar functionality for webapps

## Common functionality:
- [x] pin icon
- [x] main logo

## To be tested:
- [x] toggle pin icon
- [x] default main logo
- [x] custom main logo

## Webapps:
- [x] compose
- [x] admin
- [x] reporter

**Comment by Bojan-Svirkov** [comment]
PR: https://github.com/cortezaproject/corteza-e2e-cypress/pull/52

**Comment by Bojan-Svirkov** [comment]
https://github.com/cortezaproject/corteza-e2e-cypress/commit/fbe6de504b180162f76e1e994a819aefadbdfe16
