### ISSUE TITLE
Cypress code revision for advanced functionalities

### ISSUE THREAD

**Issue by Bojan-Svirkov** [cortezaproject/corteza-e2e-cypress#62]
Run `cypress/integration/advanced-functionalities/index.js` file and see which tests fail and fix them.

Admin
- [x] System
- [x] Compose
- [x] Automation

Compose
- [x] Namespace
- [x] Reminder

One
- [x] Custom app

Pagination
- [x] Compose

Server
- [x] Admin
- [x] Links
- [x] Remaining tests

Sidebar
- [x] Compose
- [x] Wf
- [x] Reporter

Finishing touches
- [x] Refactor test if needed
- [x] Make surer all of the tests pass when run all together

**Comment by Bojan-Svirkov** [comment]
https://github.com/cortezaproject/corteza-e2e-cypress/pull/70

**Comment by katrinDY** [comment]
for today: resolve mebers bug  and continue with  role revisioning
