### ISSUE TITLE
Add instructions on how to run CY tests locally with Docker

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza-e2e-cypress#72]

**Comment by kelanik8** [comment]
Corteza -> https://github.com/cortezaproject/corteza/pull/1596
Corteza E2E -> https://github.com/cortezaproject/corteza-e2e-cypress/pull/98

**Comment by petergrlica** [comment]
@kelanik8 Reviewed and commented.

**Comment by kelanik8** [comment]
https://github.com/cortezaproject/corteza/pull/1615
@petergrlica
